// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using Net5.AspNet.Workshop.Workshop.Api.Infrastructure.Data.Contexts;
using Net5.AspNet.Workshop.Workshop.Api.Infrastructure.Data.Entities;
using System;


namespace Net5.AspNet.Workshop.Workshop.Api.Infrastructure.Data.Contexts.Configurations
{
    public partial class EnrollmentConfiguration : IEntityTypeConfiguration<Enrollment>
    {
        public void Configure(EntityTypeBuilder<Enrollment> entity)
        {
            entity.ToTable("Enrollment", "Workshop");

            entity.Property(e => e.EnrollmentDate)
                .HasColumnType("date")
                .HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.EnrolledPerson)
                .WithMany(p => p.Enrollments)
                .HasForeignKey(d => d.EnrolledPersonId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_EnrollmentEnrolledPerson");

            entity.HasOne(d => d.EnrollmentState)
                .WithMany(p => p.Enrollments)
                .HasForeignKey(d => d.EnrollmentStateId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_EnrollmentEnrollmentState");

            entity.HasOne(d => d.Workshop)
                .WithMany(p => p.Enrollments)
                .HasForeignKey(d => d.WorkshopId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_EnrollmentWorkshop");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Enrollment> entity);
    }
}
