// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using Net5.AspNet.Workshop.Location.Api.Infrastructure.Data.Contexts.Configurations;
using Net5.AspNet.Workshop.Location.Api.Infrastructure.Data.Entities;
using System;

#nullable disable

namespace Net5.AspNet.Workshop.Location.Api.Infrastructure.Data.Contexts
{
    public partial class LocationContext : DbContext
    {
        public LocationContext()
        {
        }

        public LocationContext(DbContextOptions<LocationContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<District> Districts { get; set; }
        public virtual DbSet<Province> Provinces { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.HasAnnotation("Relational:Collation", "SQL_Latin1_General_CP1_CI_AS");

            modelBuilder.ApplyConfiguration(new Configurations.DepartmentConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.DistrictConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.ProvinceConfiguration());
            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}
