// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Net5.AspNet.Workshop.Workshop.Api.Infrastructure.Data.Entities
{
    public partial class FileDatum
    {
        public FileDatum()
        {
            WorkshopAgendaFileData = new HashSet<Workshop>();
            WorkshopCoverFileData = new HashSet<Workshop>();
        }

        public int FileDataId { get; set; }
        public string FileName { get; set; }
        public string Type { get; set; }
        public string Extension { get; set; }
        public int Size { get; set; }
        public string Path { get; set; }

        public virtual ICollection<Workshop> WorkshopAgendaFileData { get; set; }
        public virtual ICollection<Workshop> WorkshopCoverFileData { get; set; }
    }
}