// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Net5.AspNet.Workshop.IdentityProvider.Api.Infrastructure.Data.Entities
{
    public partial class Department
    {
        public Department()
        {
            Addresses = new HashSet<Address>();
            Provinces = new HashSet<Province>();
        }

        public int DepartmentId { get; set; }
        public string Description { get; set; }

        public virtual ICollection<Address> Addresses { get; set; }
        public virtual ICollection<Province> Provinces { get; set; }
    }
}